# Q4. We defined the tensor X of shape (2, 3, 4) in this section. What is the    output of len(X)?

In [8]:
import torch

In [9]:
X=torch.arange(24).reshape(2,3,4)
X
X
X
X
X
X
X
X
X
X
X
X
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [10]:
len(X)

2

# Q5. For a tensor X of arbitrary shape, does len(X) always correspond to the length of a certain axis of x? What is that axis?

# Q6. Run A / A.sum(axis=1) and see what happens. Can you analyze the reason?

In [17]:
A = torch.arange(20).reshape(5, 4)
A / A.sum(axis=1)

RuntimeError: The size of tensor a (4) must match the size of tensor b (5) at non-singleton dimension 1

# Q8. Consider a tensor with shape (2, 3, 4). What are the shapes of the summation outputs along axis 0, 1 and 2

In [19]:
X=torch.arange(24).reshape(2,3,4)
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [27]:
X.sum(axis=0), X.sum(axis=1), X.sum(axis=2)

(tensor([[12, 14, 16, 18],
         [20, 22, 24, 26],
         [28, 30, 32, 34]]),
 tensor([[12, 15, 18, 21],
         [48, 51, 54, 57]]),
 tensor([[ 6, 22, 38],
         [54, 70, 86]]))

# Q9. Feed a tensor with 3 or more axes to the linalg.norm function and observe its output. What does this function compute for tensors of arbitrary shape?

In [31]:
import torch

In [33]:
x = torch.Tensor([[[1,4], [3, 4]], 
                  [[6,4], [3, 4]]])
print(x.shape)

torch.Size([2, 2, 2])


In [35]:
torch.norm(x)

tensor(10.9087)