# Q1. Change the conditional statement X == Y in this section to X < Y or X > Y, and then see what kind of tensor you can get.
 

In [1]:
import torch
X = torch.arange(12, dtype=torch.float32).reshape((3, 4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

X>Y, X<Y

(tensor([[False, False, False, False],
         [ True,  True,  True,  True],
         [ True,  True,  True,  True]]),
 tensor([[ True, False,  True, False],
         [False, False, False, False],
         [False, False, False, False]]))

# Q2. Replace the two tensors that operate by element in the broadcasting mechanism with other shapes, e.g., 3-dimensional tensors. Is the result the same as expected?


In [6]:
a = torch.arange(9).reshape((3, 3, 1))
b = torch.arange(3).reshape((3, 1))

a+b

tensor([[[ 0],
         [ 2],
         [ 4]],

        [[ 3],
         [ 5],
         [ 7]],

        [[ 6],
         [ 8],
         [10]]])

In the above example the tensor b gets broadcasted to shape [3,3,1] and hence gets added to tensor a having the same shape.